
title: A Simple Pac-Man in Python
description: A series of videos for those learning how to program
baseurl: "/simple-pacman" # The subpath of your site, e.g. /blog
url: "https://www.mauricioaniche.com" # The base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author:
  name: Maurício Aniche
  bio: Assistant Professor in Software Engineering at TU Delft

# Contact links
twitter: https://twitter.com/mauricioaniche # Add your Twitter handle
email: M.FinavaroAniche@tudelft.nl # Add your Email address

# Hero Section
hero: true # To enable the section hero, use the value true. To turn off use the value false.
hero-title: Let's build a simple pac-man game... # Add your hero title
hero-subtitle: and improve our programming skills! # Add your hero subtitle
hero-image: images/pacman.jpg # Add background image in section hero

# Google Analytics
google-analytics: "" # Add your identifier. For example UA-99631805-1.


# Build settings
markdown: kramdown
permalink: pretty


# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages


sass:
  sass_dir: _sass
  style: compressed


collections:
  videos:
    sort_by: number
    permalink: /:name
    output: true